export const INIT_LOGIN = 'INIT_LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const REGISTRER_INIT= 'REGISTRER_INIT'
export const REGISTRER_SUCCESS = 'REGISTRER_SUCCESS'
export const REGISTRER_FAILURE = 'REGISTRER_FAILURE'