####
POST  http://localhost:8080/register
Content-Type: application/json

{
"username": "Moises",
"password": "12345678"
}

####
POST  http://localhost:8080/login
Content-Type: application/json

{
"username": "Moises",
"password": "12345678"
}

####
GET  http://localhost:8080/profile
